### ISSUE TITLE
Problem with avast antivirus

### ISSUE THREAD

**Issue by XenaFox** [dachcom-digital/jquery-doubleTapToGo#4]
Hi!
There is problem with avast antivirus -Other:Malware-gen [Trj]
https://www.virustotal.com/ru/file/98e1b3475e2568cb240726ac6edcfab418ecedf64c96649b5a9c213943368915/analysis/1458464615/

**Comment by vandres** [comment]
Can be just a mistake. Would you mind declaring it as harmless?
