### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by uniqueanurag** [dachcom-digital/jquery-doubletaptogo#6]
The code was written to handle devices that support touch so tap on menu does not go to link but rather opens up the menu.
If the device supporting touch also has a mouse and we click the category, it does nothing since menu is already open (due to hover). Second click takes user to the desired link like a double tap was intended on touch device.

Google analytics is also not able to track links , 500 error is coming

**Comment by vandres** [comment]
The first point is hard for us to test, because the lack of hardware. If you could take a look into it and make a pull request, we would be very pleased.

I don't know if the Google Analytics point is related to this plugin. Maybe you can show an example?

**Comment by uniqueanurag** [comment]
We can fix this if "e.preventDefault()" will call only on touch device please try

**Comment by marcorieser** [comment]
This seems to be fixed in version 3. @uniqueanurag can you check please?
