### ISSUE TITLE
Bug with 2 submenu

### ISSUE THREAD

**Issue by zau4man** [dachcom-digital/jquery-doubleTapToGo#8]
Simply go on one of examples https://osvaldas.info/examples/drop-down-navigation-touch-friendly-and-responsive/ with mobile phone (or developers mode in browser), then click once on the link blog, then link work. The page will change to "about", but should open a submenu of the second submenu.
Bug. 
How to fix?

![image-2016-08-26-22-08-58](https://cloud.githubusercontent.com/assets/13526431/18013820/5d8c07c8-6bd9-11e6-8dc1-52454bccec07.png)

**Comment by marcorieser** [comment]
Hi, we do not own the osvaldas examples. We just adapted his concept for our jQuery Widget. Can you reproduce your issue with our code and give us an example to look at?
